OUTFILE := data.py

default: 00 01 02

00:
	python -m metashape.inputs.python $@*/data.json | tee `echo $@*`/${OUTFILE}
01:
	python -m metashape.inputs.python $@*/data.json | tee `echo $@*`/${OUTFILE}
02:
	python -m metashape.inputs.python $@*/data.json | tee `echo $@*`/${OUTFILE}
